[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  HUGO_VERSION = "0.125.4"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://dawner.netlify.com/*"
  to = "https://dawner.top/:splat"
  force = true